**Шаг 1**
Добавить Liquibase к проекту. Создать файл для миграций с любым говорящим названием, которое относится к текущему уроку.
В качестве названия можно использовать, например: lesson-three, course-four-lesson-three, index-practice и т.д.

Критерии оценки.** Подключена зависимость liquibase-core.Создан пустой файл миграций.Настроен файл changelog-master.yml.
**Шаг 2**
Добавить два индекса, используя миграции:
1) Индекс для поиска по имени студента.
2) Индекс для поиска по названию и цвету факультета.

В файле миграций созданы два changeset с SQL-командами для создания индексов.
